### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by obycode** [hirosystems/stacks-subnets#204]
Investigate flaky tests in CI -- some tests fail, then pass with a rerun. They are likely caused by conflicts from multiple tests running in parallel.

**Comment by jbencin** [comment]
I'm trying to get an idea of the current state of this and where to start...
- Are there any particular tests that tend to fail often?
- Any noticeable pattern in the type of test that fails, or the errors they fail with?
- Unit tests, integration tests, or both?
- Can failures be be reproduced locally (without pushing to GitHub)?

**Comment by obycode** [comment]
Could you start off by reviewing the tests that failed in your PR? I just retried them - let's see if they pass this time. As @kantai said, that looked like a filesystem problem on the runner that may be both temporary and out of our control.

**Comment by jbencin** [comment]
There is already some logic in `bind_address()` in net/poll.rs to retry in the event of an `EADDRINUSE` error. However this logic is enabled by `cfg(test)`, which means it is enabled only during unit tests and NOT during integration tests. I'm changing this to `cfg(debug_assertions)` so that  `bind_address()` will be retried in all test/debug builds

**Comment by jbencin** [comment]
A couple tests that always fail on my pull requests are `build-publish` and `build-publish-stretch`. These fail on the attempt to push to DockerHub, which is controlled by this line:

```yaml
# Only push if (a tag was passed in) or (we're building a non-master branch)
          push: ${{ github.event.inputs.tag != '' || (github.ref != 'refs/heads/master') }}
```

It makes more sense to only push images for tags, since branches are usually experimental and ephemeral, and we definitely don't want to be publishing images for not-yet-approved PRs. So I'm going to change this to:

```yaml
# Only push if (a tag was passed in)
          push: ${{ github.event.inputs.tag != '' }}
```

**Comment by obycode** [comment]
Yeah, that seems reasonable to just create a new tag if you need an image published from a branch. Looking at the history though, it looks like @kantai made that change intentionally. What's the use case for that @kantai?

**Comment by kantai** [comment]
Yeah, that's fine. Historically, it was useful to get "feature builds", but just building on tags is ultimately simpler.

**Comment by obycode** [comment]
I was reviewing the failure in my PR #206 and I think the flakiness there comes from a race condition for the miner's nonce, when trying to submit transactions from the miner address while it is periodically sending `block-commit` transactions. I probably caused this with my changes and will come up with a fix for it.
